<a href="https://colab.research.google.com/github/idoyeon156-cloud/Pytorch_DeepLearning_Study/blob/main/%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

#1차원 텐서 선언과 프린트, 슬라이싱
t=torch.tensor([1., 3., 5., 7., 9., 4])
print(t)

print(t.dim())
print(t.shape)
print(t.size())

print(t[0], t[3], t[-1])
print(t[1:4], t[3:-1])
print(t[:3], t[4:])


tensor([1., 3., 5., 7., 9., 4.])
1
torch.Size([6])
torch.Size([6])
tensor(1.) tensor(7.) tensor(4.)
tensor([3., 5., 7.]) tensor([7., 9.])
tensor([1., 3., 5.]) tensor([9., 4.])


In [5]:
import torch

t= torch.tensor([[1., 3., 5.],
             [7., 9., 11.],
             [2., 4., 6.],
             [8., 10., 12.]])
print(t)

print(t.dim())
print(t.shape)

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.],
        [ 2.,  4.,  6.],
        [ 8., 10., 12.]])
2
torch.Size([4, 3])
